version: "3.9"

services:
    app:
        image: eclipse-temurin:17-jdk
        container_name: emv_java_app
        working_dir: /usr/src/app
        volumes:
            - ./app:/usr/src/app
        ports:
            - "8081:8080"
        command: java -cp "app.jar:lib/*" Main
        depends_on:
            - db

    db:
        image: postgres:15
        container_name: emv_db
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: emvdb
        volumes:
          - db_data:/var/lib/postgresql/data
        ports:
          - "5432:5432"

volumes:
    db_data:
